# Schema for the configuration files of the Hitsa settings module.

hitsa_settings.settings:
  type: config_object
  label: 'HITSA üldised seaded'
  mapping:
    general:
      type: mapping
      label: 'Haridusasutuse üldinfo'
      mapping:
        frontpage_background:
          type: integer
          label: 'Esilehe taustapilt'
        logo:
          type: integer
          label: 'Haridusasutuse logo'
        favicon:
          type: integer
          label: 'Haridusasutuse veebilehe tunnusikoon'
        address:
          type: text
          label: 'Haridusasutuse üldkontakti aadress'
        phone:
          type: text
          label: 'Haridusasutuse üldkontakti telefoni number'
        email:
          type: text
          label: 'Haridusasutuse üldkontakti e-posti aadress'
    important_contacts:
      type: mapping
      label: 'Jaluse olulisemad kontaktid'
      mapping:
        name_1:
          type: text
          label: 'Kontakti nimi'
        body_1:
          type: text
          label: 'Kontakti sisu'
        weight_1:
          type: integer
          label: 'Kaal'
        name_2:
          type: text
          label: 'Kontakti nimi'
        body_2:
          type: text
          label: 'Kontakti sisu'
        weight_2:
          type: integer
          label: 'Kaal'
        name_3:
          type: text
          label: 'Kontakti nimi'
        body_3:
          type: text
          label: 'Kontakti sisu'
        weight_3:
          type: integer
          label: 'Kaal'
        name_4:
          type: text
          label: 'Kontakti nimi'
        body_4:
          type: text
          label: 'Kontakti sisu'
        weight_4:
          type: integer
          label: 'Kaal'
    footer_quick_links:
      type: mapping
      label: 'Jaluse kiirlingid'
      mapping:
        link_name_1:
          type: text
          label: 'Veebilingi väljakuvatav nimi'
        link_url_1:
          type: text
          label: 'Veebilink'
        link_weight_1:
          type: integer
          label: 'Kaal'
        link_name_2:
          type: text
          label: 'Veebilingi väljakuvatav nimi'
        link_url_2:
          type: text
          label: 'Veebilink'
        link_weight_2:
          type: integer
          label: 'Kaal'
        link_name_3:
          type: text
          label: 'Veebilingi väljakuvatav nimi'
        link_url_3:
          type: text
          label: 'Veebilink'
        link_weight_3:
          type: integer
          label: 'Kaal'
        link_name_4:
          type: text
          label: 'Veebilingi väljakuvatav nimi'
        link_url_4:
          type: text
          label: 'Veebilink'
        link_weight_4:
          type: integer
          label: 'Kaal'
        link_name_5:
          type: text
          label: 'Veebilingi väljakuvatav nimi'
        link_url_5:
          type: text
          label: 'Veebilink'
        link_weight_5:
          type: integer
          label: 'Kaal'
        link_name_6:
          type: text
          label: 'Veebilingi väljakuvatav nimi'
        link_url_6:
          type: text
          label: 'Veebilink'
        link_weight_6:
          type: integer
          label: 'Kaal'
        link_name_7:
          type: text
          label: 'Veebilingi väljakuvatav nimi'
        link_url_7:
          type: text
          label: 'Veebilink'
        link_weight_7:
          type: integer
          label: 'Kaal'
        link_name_8:
          type: text
          label: 'Veebilingi väljakuvatav nimi'
        link_url_8:
          type: text
          label: 'Veebilink'
        link_weight_8:
          type: integer
          label: 'Kaal'
    footer_free_text_area:
      type: mapping
      label: 'Jaluse vabatekstiala'
      mapping:
        name:
          type: text
          label: 'Pealkiri'
        body:
          type: text
          label: 'Sisu'
  langcode:
    type: string
    label: 'Keeletähis'
