# Schema for the configuration files of the Hitsa settings module.

hitsa_settings.settings:
  type: config_object
  label: 'HITSA üldised seaded'
  mapping:
    general:
      type: mapping
      label: 'Haridusasutuse üldinfo'
      mapping:
        frontpage_background:
          type: integer
          label: 'Esilehe taustapilt'
        logo:
          type: integer
          label: 'Haridusasutuse logo'
        favicon:
          type: integer
          label: 'Haridusasutuse veebilehe tunnusikoon'
        address:
          type: text
          label: 'Haridusasutuse üldkontakti aadress'
        phone:
          type: text
          label: 'Haridusasutuse üldkontakti telefoni number'
        email:
          type: text
          label: 'Haridusasutuse üldkontakti e-posti aadress'
    important_contacts:
      type: mapping
      label: 'Olulisemad kontaktid'
      mapping:
        name_1:
          type: text
          label: 'Kontakti nimi'
        body_1:
          type: text
          label: 'Kontakti sisu'
        name_2:
          type: text
          label: 'Kontakti nimi'
        body_2:
          type: text
          label: 'Kontakti sisu'
        name_3:
          type: text
          label: 'Kontakti nimi'
        body_3:
          type: text
          label: 'Kontakti sisu'
        name_4:
          type: text
          label: 'Kontakti nimi'
        body_4:
          type: text
          label: 'Kontakti sisu'
  langcode:
    type: string
    label: 'Keeletähis'
