<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Cache\Cache;

function harno_pages_theme($existing, $type, $theme, $path)
{
  return [
    'galleries-page' => [
      'template' => 'galleries-page',
      'variables' => ['content' => []],
      'path' => 'themes/custom/harno_theme/templates/pages',
    ],
  ];
}
