<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Cache\Cache;

function harno_pages_theme($existing, $type, $theme, $path)
{
  return [
    'galleries-page' => [
      'template' => 'galleries-page',
      'variables' => ['content' => [],'pager'=>[],'academic_years'=>[]],
      'path' => 'themes/custom/harno_theme/templates/pages',
    ],
    'news-page' => [
      'template' => 'news-page',
      'variables' => ['content' => [],'pager'=>[],'academic_years'=>[]],
      'path' => 'themes/custom/harno_theme/templates/pages',
    ],
    'galleries-response' => [
      'template' => 'galleries-response',
      'variables' => ['content' => [],'pager'=>[],'academic_years'=>[]],
      'path' => 'themes/custom/harno_theme/templates/responses',
    ],
    'news-response' => [
      'template' => 'news-response',
      'variables' => ['content' => [],'pager'=>[],'academic_years'=>[]],
      'path' => 'themes/custom/harno_theme/templates/responses',
    ],
    'form-galleries' => [
      'template' => 'form-galleries',
      'render element' =>'children',
      'path' => 'themes/custom/harno_theme/templates/forms',
    ],
    'form-news' => [
      'template' => 'form-news',
      'render element' =>'children',
      'path' => 'themes/custom/harno_theme/templates/forms',
    ],
    'active-filters' => [
      'template' => 'active-filters',
      'render element' =>'children',
      'path' => 'themes/custom/harno_theme/templates/forms/filters',
    ],
  ];
}
/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function harno_pages_node_presave(\Drupal\node\NodeInterface $node) {
  // Allows for clearing of blocks based on node type.
  $node_type = $node->getType();
  if($node_type=='gallery') {
    $tags = ['node_type:' . $node->getType()];
    Cache::invalidateTags($tags);
  }
  if($node_type=='page') {
    \Drupal::service('cache.render')->invalidateAll();
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function harno_pages_node_delete(\Drupal\node\NodeInterface $node) {
  // Allows for clearing of blocks based on node type.
  $node_type = $node->getType();
  if($node_type == 'gallery') {
    $tags = ['node_type:' . $node->getType()];
    Cache::invalidateTags($tags);
  }
  if($node_type == 'page') {
    \Drupal::service('cache.render')->invalidateAll();
  }
}
