<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Cache\Cache;

function harno_pages_theme($existing, $type, $theme, $path)
{
  return [
    'galleries-page' => [
      'template' => 'galleries-page',
      'variables' => ['content' => [],'pager'=>[]],
      'path' => 'themes/custom/harno_theme/templates/pages',
    ],
  ];
}
/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function harno_pages_node_presave(\Drupal\node\NodeInterface $node) {
  // Allows for clearing of blocks based on node type.
  $node_type = $node->getType();
  if($node_type=='gallery') {
    $tags = ['node_type:' . $node->getType()];
    Cache::invalidateTags($tags);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function harno_pages_node_delete(\Drupal\node\NodeInterface $node) {
  // Allows for clearing of blocks based on node type.
  $node_type = $node->getType();
  if($node_type=='gallery') {
    $tags = ['node_type:' . $node->getType()];
    Cache::invalidateTags($tags);
  }
}
