label: 'Keelte haldamine'
tips:
  language-edit-overview:
    label: 'Keelte haldamine'
    body: '<p>This page provides the ability to edit a language on your site, including custom languages.</p>'
  language-edit-langcode:
    label: 'Keele kood'
    body: '<p>You cannot change the code of a language on the site, since it is used by the system to keep track of the language.</p>'
  language-edit-label:
    label: 'Keele nimetus'
    body: '<p>The language name is used throughout the site for all users and is written in English. Names of built-in languages can be translated using the Interface Translation module, and names of both built-in and custom languages can be translated using the Configuration Translation module.</p>'
  language-edit-direction:
    label: 'Keele suund'
    body: '<p>Choose if the language is a "Left to right" or "Right to left" language.</p><p>Note that not all themes support "Right to left" layouts, so test your theme if you are using "Right to left".</p>'
  language-edit-continue:
    label: Jätkub
