label: Avaleht
description: 'Kogu avalehele määratud sisu.'
display:
  default:
    display_options:
      empty:
        title:
          title: 'Tere tulemast lehele [site:name]'
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
  feed_1:
    display_title: Andmevoog
