label: Kommentaarid
display:
  default:
    display_options:
      pager:
        options:
          tags:
            previous: '‹ eelmine'
            next: 'järgmine ›'
            first: '« esimene'
            last: 'viimane »'
      fields:
        subject:
          label: Teema
        entity_id:
          label: Postitatud
      filters:
        subject:
          expose:
            label: Teema
        combine:
          expose:
            label: 'Autori nimi'
      title: Kommentaarid
      empty:
        area_text_custom:
          content: 'Kommentaarid puuduvad.'
      use_more_text: veel
  page_published:
    display_title: 'Avaldatud kommentaarid'
    display_options:
      menu:
        title: Kommentaarid
        description: 'Avaldatud kommentaarid'
      display_description: 'Heaks kiidetud kommentaaride nimekiri.'
  page_unapproved:
    display_title: 'Heakskiitmata kommentaarid'
    display_options:
      menu:
        title: 'Heakskiitmata kommentaarid'
        description: 'Kinnitamata kommentaarid'
      display_description: 'Kinnitamata kommentaaride nimekiri.'
      filters:
        subject:
          expose:
            label: Teema
        combine:
          expose:
            label: 'Autori Nimi'
      fields:
        subject:
          label: Teema
        entity_id:
          label: Postitatud
