label: 'Taksonoomia termin'
description: 'Teatud taksonoomia termiga seotud sisu.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
  feed_1:
    display_title: Andmevoog
