label: 'Hiljutine sisu'
description: 'Viimati lisatud sisu.'
display:
  default:
    display_options:
      title: 'Hiljutine sisu'
      empty:
        area_text_custom:
          content: 'Sisu puudub.'
  block_1:
    display_title: Plokk
