label: Kasutajad
description: 'Sinu lehel käivate inimeste leidmine ja haldus.'
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Tühista
      fields:
        user_bulk_form:
          label: Massuuendus
        name:
          label: Kasutajanimi
        status:
          label: Staatus
          settings:
            format_custom_true: Aktiivne
            format_custom_false: Blokeeritud
        roles_target_id:
          label: Rollid
        created:
          label: 'Liikmeks oldud aeg'
        access:
          label: 'Последнее посещение'
      filters:
        combine:
          expose:
            label: 'Nimi või e-post sisaldab'
        status:
          group_info:
            label: Staatus
            group_items:
              1:
                title: Aktiivne
              2:
                title: Blokeeritud
        roles_target_id:
          expose:
            label: Roll
        permission:
          expose:
            label: Õigus
      title: Kasutajad
      empty:
        area_text_custom:
          content: 'Inimesed puuduvad.'
      use_more_text: veel
  page_1:
    display_options:
      menu:
        title: Nimekiri
        description: 'Sinu lehel käivate inimeste leidmine ja haldus.'
      tab_options:
        title: Kasutajad
        description: 'Kasutajakontode, rollide ja õiguste haldamine.'
