label: 'Hiljutine sisu'
description: 'Viimati lisatud sisu.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
      title: 'Hiljutine sisu'
      empty:
        area_text_custom:
          content: 'Sisu puudub.'
  block_1:
    display_title: Plokk
