label: Arhiiv
description: 'Kogu sisu, kuu kaupa.'
display:
  default:
    display_options:
      title: 'Igakuine arhiiv'
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
  block_1:
    display_title: Plokk
