label: Kommentaarid
description: 'Find and manage comments.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ eelmine'
            next: 'järgmine ›'
            first: '« esimene'
            last: 'viimane »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        subject:
          label: Teema
        entity_id:
          label: Postitatud
      filters:
        subject:
          expose:
            label: Teema
        combine:
          expose:
            label: 'Autori nimi'
        langcode:
          expose:
            label: Language
      title: Kommentaarid
      empty:
        area_text_custom:
          content: 'Kommentaarid puuduvad.'
      use_more_text: veel
  page_published:
    display_title: 'Avaldatud kommentaarid'
    display_options:
      menu:
        title: Kommentaarid
        description: 'Avaldatud kommentaarid'
      display_description: 'Heaks kiidetud kommentaaride nimekiri.'
  page_unapproved:
    display_title: 'Heakskiitmata kommentaarid'
    display_options:
      menu:
        title: 'Heakskiitmata kommentaarid'
        description: 'Kinnitamata kommentaarid'
      display_description: 'Kinnitamata kommentaaride nimekiri.'
      filters:
        subject:
          expose:
            label: Teema
        combine:
          expose:
            label: 'Autori Nimi'
        langcode:
          expose:
            label: Language
      fields:
        subject:
          label: Teema
        entity_id:
          label: Postitatud
