label: 'Sisseloginud kasutajate infoplokk'
description: 'Kuvab aktiivsete kasutajate kogunumbrit ja viimati aktiivsete kasutajate kasutaja nimesid.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      filters:
        access:
          expose:
            label: 'Viimane külastus'
            description: 'Pärast viimase lehe vaatamist on kasutaja online'
      title: 'Lehel olevad kasutajad'
      header:
        result:
          content: 'Hetkel on lehel @total kasutajat.'
      empty:
        area_text_custom:
          content: 'Hetkel on lehel 0 kasutajat.'
  who_s_online_block:
    display_title: 'Lehel olevad kasutajad'
    display_options:
      block_description: 'Lehel olevad kasutajad'
      display_description: 'Nimekiri kasutajatest kes on hetkel sisse logitud.'
