label: Sõnastik
description: 'Kogu sisu, tähestikuliselt.'
display:
  default:
    display_options:
      fields:
        title:
          label: Pealkiri
        changed:
          label: 'Viimati uuendatud'
  attachment_1:
    display_title: Manus
  page_1:
    display_options:
      menu:
        title: Sõnastik
