general:
  frontpage_background: 0
  logo: 0
  favicon: 0
  address: 'Müüri 4, Olustvere, Põhja-Sakala vald, 70401 Viljandi maakond'
  phone: '6584930'
  email: onnepalu@mail.ee
important_contacts:
  name_1: ' Direktor Aleksandr Skidantsuk'
  body_1: '(+372) 507 3849'
  weight_1: -10
  name_2: 'Täiendkoolituse osakonna juhataja'
  body_2: aleksandr.skidantsuk@mehaanikakool.ee
  weight_2: -9
  name_3: 'Registrikood ja arvenumber'
  body_3: ''
  weight_3: -8
  name_4: Vastuvõtt
  body_4: '+372 437 4244 / vastuvott@olustvere.edu.ee'
  weight_4: -7
footer_socialmedia_links:
  link_icon_1: mdi-instagram
  link_name_1: Instagram
  link_url_1: 'https://www.instagram.com/vjktoimetus/'
  link_weight_1: -10
  link_icon_2: mdi-linkedin
  link_name_2: LinkedIn
  link_url_2: 'https://www.linkedin.com/?trk=public_jobs_nav-header-logo'
  link_weight_2: -9
  link_icon_3: mdi-facebook
  link_name_3: Facebook
  link_url_3: 'https://www.facebook.com/SakuGumnaasium/'
  link_weight_3: -8
  link_icon_4: mdi-youtube
  link_name_4: Youtube
  link_url_4: 'https://www.youtube.com/channel/UCpyufRRdMNyD23JesPMvSLQ'
  link_weight_4: -7
  link_icon_5: ''
  link_name_5: ''
  link_url_5: ''
  link_weight_5: -6
  link_icon_6: ''
  link_name_6: ''
  link_url_6: ''
  link_weight_6: -5
  link_icon_7: ''
  link_name_7: ''
  link_url_7: ''
  link_weight_7: -4
  link_icon_8: ''
  link_name_8: ''
  link_url_8: ''
  link_weight_8: -3
  link_icon_9: ''
  link_name_9: ''
  link_url_9: ''
  link_weight_9: -2
footer_quick_links:
  link_name_1: 'Üks lihtne lehekülg testiks'
  link_entity_1: 5
  link_url_1: ''
  link_weight_1: -10
  link_name_2: 'Õpikute laenutamine 2020/21 õppeaastaks'
  link_entity_2: 6
  link_url_2: ''
  link_weight_2: -9
  link_name_3: ''
  link_entity_3: null
  link_url_3: ''
  link_weight_3: -8
  link_name_4: ''
  link_entity_4: null
  link_url_4: ''
  link_weight_4: -7
  link_name_5: ''
  link_entity_5: null
  link_url_5: ''
  link_weight_5: -6
  link_name_6: ''
  link_entity_6: null
  link_url_6: ''
  link_weight_6: -5
  link_name_7: ''
  link_entity_7: null
  link_url_7: ''
  link_weight_7: -4
  link_name_8: ''
  link_entity_8: null
  link_url_8: ''
  link_weight_8: -3
footer_free_text_area:
  name: 'Vabatekstiala pealkiri'
  body: 'Vabatekstiala sisu'
footer_copyright:
  name: '© 2020 - 2021 Õnnevälja Ühisgümnaasium'
automatic_generation_academic_year:
  'on': true
  date: 15.06.
frontpage_quick_links:
  link_name_1: Tunniplaan
  link_entity_1: 1
  link_url_1: ''
  link_weight_1: -10
  link_name_2: Galerii
  link_entity_2: 4
  link_url_2: ''
  link_weight_2: -9
  link_name_3: ''
  link_entity_3: null
  link_url_3: ''
  link_weight_3: -8
  link_name_4: ''
  link_entity_4: null
  link_url_4: ''
  link_weight_4: -7
  link_name_5: ''
  link_entity_5: null
  link_url_5: ''
  link_weight_5: -6
  link_name_6: ''
  link_entity_6: null
  link_url_6: ''
  link_weight_6: -5
  link_name_7: ''
  link_entity_7: null
  link_url_7: ''
  link_weight_7: -4
  link_name_8: ''
  link_entity_8: null
  link_url_8: ''
  link_weight_8: -3
langcode: et
_core:
  default_config_hash: WmFHeq2GiSpb8GHe19n_nYjMMtCcCe0p8MMBd2of-zA
news_our_story:
  name: 'Kooli blogi'
