name: 'HITSA seadistused'
type: module
description: 'HITSA veebiplatvormide seadistused'
core: 8.x
core_version_requirement: ^8 || ^9
package: 'HITSA'
configure: hitsa_settings.hitsa_settings_form
dependencies:
  - linkit:linkit

version: '8.x-dev'
project: 'hitsa_settings'
