name: 'Veebiplatvormi seadistused'
type: module
description: 'Veebiplatvormide seadistused'
core: 8.x
core_version_requirement: ^8 || ^9
package: 'Veebiplatvorm'
configure: hitsa_settings.hitsa_settings_form
