<?php

/**
 * @file
 * Contains pria_settings.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hitsa_settings_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pria_settings module.
    case 'help.page.hitsa_settings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('HITSA settings module') . '</p>';
      return $output;

    default:
  }
}
/**
 * Implements hook_theme().
 */
function hitsa_settings_theme($existing, $type, $theme, $path) {
  $items = [];
  global $base_path;
  $theme_path = $theme = \Drupal::theme()->getActiveTheme()->getPath();
  $path = $base_path.'/'.$theme_path.'/templates/blocks';
  $items['hitsa_social_block'] = [
    'variables' => [
      'data' => []
    ],
    'path' => $path,
  ];
  $items['hitsa_important_contacts_block'] = [
    'variables' => [
      'data' => []
    ],
    $path => $path,
  ];
  return $items;
}
