harno_settings.admin_index:
  title: Veebiplatvorm
  route_name: harno_settings.admin_index
  parent: system.admin_config
  description: 'Configure Veebiplatvorm settings.'
  position: left
  weight: -40
harno_settings.settings_form:
  title: 'Üldised seaded'
  description: 'Kasutaja saab sisestada ja muuta lehe üldseadistuse elemente, mis kuvatakse avaliku vaate avalehel, jaluses või päises.
  Näiteks haridusasutuse üldised kontaktid, haridusasutuse sotsiaalmeedia lingid, avalehe ja jaluse kiirlingid,
  jaluse vabatekstiala ja jaluses kuvatav kasutusõiguste märkus.'
  route_name: harno_settings.settings_form
  parent: harno_settings.admin_index
